---
- hosts: mnodes
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: add key 
        apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=E56151BF 
      - name: get destro 
        command: lsb_release -is 
        register: DISTRO 
      - name: get destro 
        command: lsb_release -cs 
        register: CODENAME 
      - debug: var=CODENAME
      - name: add repo
        apt_repository: repo="deb http://repos.mesosphere.com/{{ DISTRO.stdout | lower }} {{ CODENAME.stdout }} main" state=present
      - name: install mesos 
        apt: name=mesos state=latest force=yes update_cache=yes 
      - name: stop zookeeper
        service: name=zookeeper state=stopped enabled=no
      - name: update hosts file
        template: src=./hosts.j2 dest=/etc/hosts
      - name: zk file 
        template: src=./zk.j2 dest=/etc/mesos/zk
      - name: quorum file
        template: src=./quorum.j2 dest=/etc/mesos-master/quorum
      - name: start master
        service: name=mesos-master state=started
      - name: start slave 
        service: name=mesos-slave state=started
