---
- hosts: mnodes
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: stop zookeeper
        service: name=zookeeper state=stopped enabled=no
      - name: start master
        service: name=mesos-master state=started enabled=yes
      - name: start slave 
        service: name=mesos-slave state=started enabled=yes
      - name: restart docker 
        service: name=docker state=restarted
#start marathon
- hosts: marathon
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: start marathon
        service: name=marathon state=started enabled=yes
#start zookeeper
- hosts: zookeeper
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: start zookeeper
        service: name=zookeeper state=started enabled=yes
#start chronos
- hosts: chronos
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: start chronos
        service: name=chronos state=started enabled=yes
