ANSIBLE_GROUPS = {
  "elk" => ["elk1"],
  "all_groups:children" => ["elk"]
}


Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4084 
    end
    config.vm.define "elk1" do |elk1|
        elk1.vm.network "private_network", ip: "192.168.33.19"
        elk1.vm.hostname = "elk1"
        elk1.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.groups = ANSIBLE_GROUPS
        end
    end
end
